### ISSUE TITLE
Problem with carbon date (Pimcore 4.4.0)

### ISSUE THREAD

**Issue by Yivan** [dachcom-digital/pimcore-news#2]
Hello,

I tried the plug in and it seems nice to make easily some news listing.

I have an error, because Carbon is used now, on file:
`\plugins\News\views\scripts\news\detail.php`
line 34:
`<?= $this->news->getDate()->get('dd.MM.YYYY'); ?>`
need to be replaced by:
`<?= $this->news->getDate()->format('d.m.y'); ?>`

By the way is there somewhere a documentation ?
I think I get the overall comprehesion, but for instance the purpose of the objectBrick to the "news" model class is to extend it ? Is there any hook/event/extending possibility ? (how to overide the default views for instance ?)

Thanks for this nice plugin!

**Comment by Yivan** [comment]
Ouch just see an issue was already opened, maybe the same:
https://github.com/dachcom-digital/pimcore-news/issues/1

Is it going to be corrected as the issue seems to have been open a long times ago ?
Is the project still alive and realiable ?
Thanks.

**Comment by solverat** [comment]
Yes, this fix will be released in 1.2
