### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable on saving category

### ISSUE THREAD

**Issue by mittererr** [dachcom-digital/pimcore-news#21]
I get a warning when saving news categories:

**_Warning: count(): Parameter must be an array or an object that implements Countable_**

Parameters in SEO Tab are empty.

In dev.log I can find:
Warning: count(): Parameter must be an array or an object that implements Countable in /Applications/MAMP/htdocs/thermik.test/vendor/dachcom-digital/news/src/NewsBundle/EventListener/NewsSeoListener.php:173

**Comment by solverat** [comment]
fixed with 2.1.1.
