### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by ITspirit** [dachcom-digital/pimcore-news#30]
I've a really fresh installation of pimcore with slight modifications. It's Pimcore 5.5.2 where pimcore is loaded as composer dependency (like in the skeleton).
PHP Version is 7.2.10

I've added pimcore-news as a dependency and now i get these warning below if i insert the aerablock "news" in the page.

Not sure if there are additional configs needed or what's the reason of these warning. 

`
Warning: count(): Parameter must be an array or an object that implements Countable
#0 /var/www/pimcore/releases/21/vendor/dachcom-digital/news/src/NewsBundle/Document/Areabrick/News/News.php(135): NewsBundle\Model\Entry::getEntriesPaging(Array)
#1 /var/www/pimcore/releases/21/vendor/pimcore/pimcore/lib/Document/Tag/TagHandler.php(226): NewsBundle\Document\Areabrick\News\News->action(Object(Pimcore\Model\Document\Tag\Area\Info)) 
#2 /var/www/pimcore/releases/21/vendor/pimcore/pimcore/lib/Document/Tag/DelegatingTagHandler.php(128): Pimcore\Document\Tag\TagHandler->renderAreaFrontend(Object(Pimcore\Model\Document\Tag\Area\Info)) 
#3 /var/www/pimcore/releases/21/vendor/pimcore/pimcore/models/Document/Tag/Areablock.php(198): Pimcore\Document\Tag\DelegatingTagHandler->renderAreaFrontend(Object(Pimcore\Model\Document\Tag\Area\Info)) 
#4 /var/www/pimcore/releases/21/vendor/pimcore/pimcore/models/Document/Tag/Areablock.php(155): Pimcore\Model\Document\Tag\Areablock->content() 
#5 /var/www/pimcore/releases/21/vendor/pimcore/pimcore/models/Document/Tag/Areablock.php(90): Pimcore\Model\Document\Tag\Areablock->loop() 
#6 /var/www/pimcore/releases/21/vendor/pimcore/pimcore/models/Document/Tag/Areablock.php(78): Pimcore\Model\Document\Tag\Areablock->frontend() 
#7 /var/www/pimcore/releases/21/vendor/pimcore/pimcore/models/Document/Tag.php(456): Pimcore\Model\Document\Tag\Areablock->admin() 
#8 /storage1/pimcore/var/cache/dev/twig/7b/7bd4c3c26a5b80452dfbe244d7c3f0534f1af62f433ad7fb77c8ded38abeed33.php(89): Pimcore\Model\Document\Tag->__toString() 
#9 /var/www/pimcore/releases/21/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_b28b1a6628e32401c1be4cfab65b3c6391fb592b2339be033686068bd0bf9a5f->block_content(Array, Array) 
#10 /storage1/pimcore/var/cache/dev/twig/69/6999762228f5d3c501dd443844ce806578477426bc37728357b180f60d56bf30.php(49): Twig_Template->displayBlock('content', Array, Array) 
#11 /var/www/pimcore/releases/21/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_f3c2b94f71f140cd86722782141b69f1a034fcf1a78b1f09af0a4d44f0c3eb98->doDisplay(Array, Array) 
#12 /var/www/pimcore/releases/21/vendor/twig/twig/lib/Twig/Template.php(367): Twig_Template->displayWithErrorHandling(Array, Array) 
#13 /storage1/pimcore/var/cache/dev/twig/7b/7bd4c3c26a5b80452dfbe244d7c3f0534f1af62f433ad7fb77c8ded38abeed33.php(40): Twig_Template->display(Array, Array) 
#14 /var/www/pimcore/releases/21/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_b28b1a6628e32401c1be4cfab65b3c6391fb592b2339be033686068bd0bf9a5f->doDisplay(Array, Array) 
#15 /var/www/pimcore/releases/21/vendor/twig/twig/lib/Twig/Template.php(367): Twig_Template->displayWithErrorHandling(Array, Array) 
#16 /var/www/pimcore/releases/21/vendor/twig/twig/lib/Twig/Template.php(375): Twig_Template->display(Array) 
#17 /var/www/pimcore/releases/21/vendor/symfony/symfony/src/Symfony/Bridge/Twig/TwigEngine.php(49): Twig_Template->render(Array) 
#18 /var/www/pimcore/releases/21/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/TwigEngine.php(45): Symfony\Bridge\Twig\TwigEngine->render('Project/de/blog.h...', Array) 
#19 /var/www/pimcore/releases/21/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/TwigEngine.php(72): Symfony\Bundle\TwigBundle\TwigEngine->render('Project/de/blog.h...', Array) 
#20 /var/www/pimcore/releases/21/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Templating/DelegatingEngine.php(51): Symfony\Bundle\TwigBundle\TwigEngine->renderResponse('Project/de/blog.h...', Array, Object(Symfony\Component\HttpFoundation\Response)) 
#21 /var/www/pimcore/releases/21/vendor/sensio/framework-extra-bundle/EventListener/TemplateListener.php(107): Symfony\Bundle\FrameworkBundle\Templating\DelegatingEngine->renderResponse('Project/de/blog.h...', Array) 
#22 /var/www/pimcore/releases/21/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(104): Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener->onKernelView(Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent), 'kernel.view', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher)) 
#23 /var/www/pimcore/releases/21/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(212): Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent), 'kernel.view', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)) 
#24 /var/www/pimcore/releases/21/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.view', Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent)) 
#25 /var/www/pimcore/releases/21/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php(139): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.view', Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent)) 
#26 /var/www/pimcore/releases/21/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(156): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('kernel.view', Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent)) 
#27 /var/www/pimcore/releases/21/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) 
#28 /var/www/pimcore/releases/21/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(200): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#29 /var/www/pimcore/releases/21/web/app.php(42): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) 
#30 {main}
`

**Comment by solverat** [comment]
Hey @ITspirit, I think this has already been fixed on dev-master. Could you check out the latest dev-master and check it again?

**Comment by ITspirit** [comment]
The issue as described from me above - yes - seems fixed on dev-master.

But still have a similar issue on creating news. On "save & publish" of a new news entry i get these popup:

`Server threw exception - could not perform action. Please reload the admin interface and try again.

Timestamp: Fri Oct 19 2018 10:52:00 GMT+0200 (Mitteleuropäische Sommerzeit)
Status: 500 | 
URL: /admin/object/save?task=unpublish
Method: PUT
Message: Warning: count(): Parameter must be an array or an object that implements Countable
`

The error appears only, if you enter a "Name" (above the Lead Field) - in the Language Tabs.

**Comment by solverat** [comment]
hey @ITspirit, just found it - fixed!
